dhcp_global_default_lease_time: 43200
dhcp_global_domain_name: avalon.lan
dhcp_global_routers: 172.16.255.254
dhcp_global_domain_name_servers:
  - 192.0.2.10
  - 192.0.2.11
dhcp_subnets:
  - ip: 172.16.0.0
    netmask: 255.255.0.0
    range_begin: 172.16.192.1
    range_end: 172.16.255.253  
dhcp_hosts:
  - name: vm1
    mac: '08:00:27:B6:EE:F2'
    ip: 172.16.128.27
