rhbase_firewall_allow_services:
  - samba
  - ftp
rhbase_user_groups:
  - management
  - technical
  - sales
  - it
rhbase_users:
  - name: maxim
    groups:
      - it
      - users
      - wheel
    password: '{{ maxim }}'
  - name: stevenh
    groups:
      - management
      - users
    password: '{{ stevenh }}'
  - name: stevenv
    groups:
      - users
      - technical
    password: '{{ stevenv }}'
  - name: leend
    groups:
      - technical
      - users
    password: '{{ leend }}'
  - name: svena
    groups:
      - sales
      - users
    password: '{{ svena }}'
  - name: nehirb
    groups:
      - it
      - users
    password: '{{ nehirb }}'
  - name: alexanderd
    groups:
      - technical
      - users
    password: '{{ alexanderd }}'
  - name: krisv
    groups:
      - management
      - users
    password: '{{ krisv }}'
  - name: benoitp
    groups:
      - sales
      - users
    password: '{{ benoitp }}'
  - name: anc
    groups:
      - technical
      - users
    password: '{{ anc }}'
  - name: elenaa
    groups:
      - management
      - users
    password: '{{ elenaa }}'
  - name: evyt
    groups:
      - technical
      - users
    password: '{{ evyt }}'
  - name: christophev
    groups:
      - it
      - users
    password: '{{ christophev }}'
  - name: stefaanv
    groups:
      - technical
      - users
    password: '{{ stefaanv }}'

samba_netbios_name: files
samba_server_string: 'Welcome to the file server'
samba_workgroup: AVALON
samba_load_homes: true
samba_load_printers: false

samba_log: /var/log/samba.log
samba_log_size: 60000
samba_log_level: '3 passdb:5 auth:10 winbind:2 '

samba_users:
  - name: maxim
    password: '{{ maxim }}'
  - name: stevenh
    password: '{{ stevenh }}'
  - name: stevenv
    password: '{{ stevenv }}'
  - name: leend
    password: '{{ leend }}'
  - name: svena
    password: '{{ svena }}'
  - name: nehirb
    password: '{{ nehirb }}'
  - name: alexanderd
    password: '{{ alexanderd }}'
  - name: krisv
    password: '{{ krisv }}'
  - name: benoitp
    password: '{{ benoitp }}'
  - name: anc
    password: '{{ anc }}'
  - name: elenaa
    password: '{{ elenaa }}'
  - name: evyt
    password: '{{ evyt }}'
  - name: christophev
    password: '{{ christophev }}'
  - name: stefaanv
    password: '{{ stefaanv }}'

samba_shares:
  - name: public
    group: users
    public: yes
    write_list: +users
    valid_users: +users
    setype: public_content_t
    directory_mode: '0770'
  - name: it
    group: it
    write_list: +it
    valid_users: +management,+it
    directory_mode: '0770'
  - name: management
    group: management
    write_list: +management
    valid_users: +management
    directory_mode: '0770'
  - name: technical
    group: technical
    write_list: +technical
    valid_users: +users
    directory_mode: '0775'
  - name: sales
    group: sales
    write_list: +sales
    valid_users: +management, +sales
    directory_mode: '0770'

vsftpd_anonymous_enable: false 
vsftpd_local_enable: true
vsftpd_write_enable: true
vsftpd_local_root: /srv/shares
vsftpd_extra_permissions:
  - folder: "/srv/shares/sales"
    entity: "management"
    etype: "group"
    permissions: "r-x"
    folder: "/srv/shares/it"
    entity: "management"
    etype: "group"
    permissions: "r-x"



