rhbase_firewall_allow_services:
  - http
  - https
rhbase_firewall_allow_ports:
  - 587/tcp
  - 465/tcp
  - 110/tcp
  - 143/tcp
httpd_ssl_certificate_key_file: 'ca.key'
httpd_ssl_certificate_file: 'ca.crt'
mariadb_root_password: 'root'
mariadb_databases:
  - name: wordpress_db
mariadb_users:
  - name: wordpress_usr
    password: wordpress
    priv: 'wordpress_db.*:ALL'
wordpress_database: wordpress_db
wordpress_user: wordpress_usr
wordpress_password: wordpress

fail2ban_loglevel: 3

