# group_vars/all.yml
# Variables visible to all nodes
---
rhbase_install_packages:
  - bash-completion
  - bind-utils
  - git
  - nano
  - tree
  - vim-enhanced
  - wget
rhbase_firewall_allow_services:
  - http
  - https
