# site.yml
---
# LAMP
- hosts: pu004
  become: true
  roles:
    - bertvv.rh-base
    - bertvv.httpd
    - bertvv.mariadb
    - bertvv.wordpress
    - nbigot.ansible-fail2ban

# MasterDNS
- hosts: pu001
  become: true
  vars:
   - api_key: '0643a14d6101fda2f54f507d23732fcc'
  roles:
    - bertvv.rh-base
    - bertvv.bind
    - maximeeckhout.datadog

#SlaveDNS
- hosts: pu002
  become: true
  roles:
    - bertvv.rh-base
    - bertvv.bind

# FileServer
- hosts: pr011
  become: true
  vars_files:
    - vars/wachtwoorden.yml
  roles:
    - bertvv.rh-base
    - bertvv.samba
    - bertvv.vsftpd

# DHCPServer
- hosts: pr001
  become: true
  roles:
    - bertvv.rh-base
    - bertvv.dhcp


