# site.yml
---
- hosts: pu004
  become: true
  pre_tasks:
    - name: Include rh_base variables
      include_vars: "vars/var_rh-base.yml"
    - name: Include httpd variables
      include_vars: "vars/var_httpd.yml"
    - name: Include mariadb variables
      include_vars: "vars/var_mariadb.yml"
    - name: Include wordpress variables
      include_vars: "vars/var_wordpress.yml"
  roles:
    - bertvv.rh-base
    - bertvv.httpd
    - bertvv.mariadb
    - bertvv.wordpress

#- hosts: pu001
#  become: true

#- hosts:pu002
#  become: true
